### ISSUE TITLE
After updating com.android.tools.build:gradle to 8.1.2 Release build fails

### ISSUE THREAD

**Issue by AlexNikolaevSwTecNN** [stevesaliman/gradle-properties-plugin#46]
com.android.tools.build:gradle:8.1.2

Release build fails on minifyReleaseWithR8 task.

```
> Task :androidApp:minifyReleaseWithR8 FAILED
AGPBI: {"kind":"error","text":"com.android.tools.r8.ResourceException: com.android.tools.r8.internal.Ub: I/O exception while reading '.../androidApp/build/intermediates/merged_java_res/release/base.jar': .../androidApp/build/intermediates/merged_java_res/release/base.jar","sources":[{"file":".../androidApp/build/intermediates/merged_java_res/release/base.jar"}],"tool":"R8"}

...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':androidApp:minifyReleaseWithR8'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
   > Compilation failed to complete, origin: .../androidApp/build/intermediates/merged_java_res/release/base.jar
```
